# Node.js 기반 환경 설정
FROM node:20

# 작업 디렉토리 생성
WORKDIR /app

# 의존성 설치
COPY subscription/package*.json ./
RUN npm install

# 소스 복사
COPY subscription/ .

# 포트 설정 (예: 4000번 사용한다고 가정)
EXPOSE 4000

# 실행 명령
CMD ["node", "index.js"]
