version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: newsum-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: newsum-backend
    ports:
      - "3000:3000"
    depends_on:
      - subscription

  subscription:
    build:
      context: ./subscription
    container_name: newsum-subscribe
    ports:
      - "4000:4000"
